# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-21 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='image',
        ),
    ]
