# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
