# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 17:00
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.image_upload_to)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-created_at']},
        ),
    ]
