# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 18:38
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tour_down'),
        ('main', '0003_auto_20170127_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingsToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=base.models.image_upload_to)),
                ('tours', models.ManyToManyField(to='base.Tour')),
            ],
        ),
    ]
