# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 17:36
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tour_down'),
        ('main', '0004_thingstodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=base.models.image_upload_to)),
                ('link', models.URLField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('initial', models.DateField()),
                ('final', models.DateField()),
                ('people', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('category_of_tour', models.CharField(choices=[('Luxe', 'Luxe'), ('Standart', 'Standart'), ('Budget', 'Budget')], max_length=100)),
                ('transport', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100)),
                ('food', models.CharField(choices=[('Full board', '1'), ('Half board', '2'), ('Bed breakfast', '3'), ('Room only', '4')], max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tour')),
            ],
        ),
    ]
