# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hotel_tripplanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplanner',
            name='category_of_tour',
            field=models.CharField(blank=True, choices=[('Luxe', 'Luxe'), ('Standart', 'Standart'), ('Budget', 'Budget')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tripplanner',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripplanner',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tripplanner',
            name='food',
            field=models.CharField(blank=True, choices=[('Full board', 'Full board'), ('Half board', 'Half board'), ('Bed breakfast', 'Bed breakfast'), ('Room only', 'Room only')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tripplanner',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Hotel'),
        ),
        migrations.AlterField(
            model_name='tripplanner',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tour'),
        ),
        migrations.AlterField(
            model_name='tripplanner',
            name='transport',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True),
        ),
    ]
