# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='down',
            field=models.BooleanField(default=True),
        ),
    ]
