# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-05 15:44
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tour_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=base.models.image_upload_to),
        ),
    ]
